title: Koja
brand: The Koja programming language
tagline: Joy, compiled.
description: Koja is a programming language to spark joy. Statically typed, compiled to native binaries, with friendly syntax and effortless concurrency. Now in alpha.
url: https://kojalang.org
lang: en
author: Henry Popp

twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /static/og-image.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - og-image.html
  - vendor
  - .github
